[package]
name = "rustkeys"
version = "0.2.29"
edition = "2021"

[lib]
name = "rustkeys"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
fastrand = "1.8.0"
num-bigint = "0.4.3"
rand = "0.8.4"
